name: Call Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  call-reusable-workflow:
    uses: bedarosa/ci-cd-workflows/.github/workflows/reusable-workflow.yml@master
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
