name: Call Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  call-reusable-workflow:
    uses: bedarosa/ci-cd-workflows/.github/workflows/test-secret-workflow.yml.yml@master
    secrets:
      API_KEY: ${{ secrets.TEST_SECRET }}
